# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181217_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='medId',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='pacId',
            new_name='paciente',
        ),
    ]
